### ISSUE TITLE
[Starbound] Server Script Request

### ISSUE THREAD

**Issue by DSDV** [dgibbs64/linuxgameservers#268] opened 2015-01-13 15:33 UTC
Hello,
i use 3 of your scripts and since i migrated to a bigger server i dont host a server without one.
So i a couple month the 1.0 version of a Game called Starbound is announced.

My question is: is it possible that youll make a script for that game(server)?

Here are the Links to the game:
http://playstarbound.com/
http://store.steampowered.com/app/211820/
https://en.wikipedia.org/wiki/Starbound

with best +DS_DV+

PS: it would be very cool if there ll be a script for SB :D

**Comment by Scarsz** [comment] 2015-01-13 15:47
https://github.com/dgibbs64/linuxgameservers/issues/37

I'll work on this more today, a script will probably released today or tomorrow.

**Comment by DSDV** [comment] 2015-01-13 19:11
oh thats fast and great :)

when 1.0 stable will release ill test it and set up a server :)

**Comment by dgibbs64** [comment] 2015-01-22 21:30
closing as duplicate of #37

**Closed by dgibbs64** 2015-01-22 21:30 UTC
Labels: enhancement
